# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 10:59
from __future__ import unicode_literals

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=70)),
                ('long_description', models.TextField()),
                ('release_date', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=70)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(5)])),
                ('author_image', models.ImageField(upload_to=books.models.profile_directory_path)),
                ('book_image', models.ImageField(upload_to=books.models.book_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
