# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 11:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160206_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
